-- Migration: Create spreadsheet_rows and spreadsheet_sub_rows tables with appropriate columns and Row Level Security (RLS) policies to allow public access (since no authentication is currently implemented).
-- Executed at: 2026-02-12T22:30:34Z
-- Generated by AI Agent

-- Create the main rows table
CREATE TABLE IF NOT EXISTS spreadsheet_rows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  col_a TEXT DEFAULT '',
  col_b TEXT DEFAULT '',
  col_c TEXT DEFAULT '',
  col_d TEXT DEFAULT ''
);

-- Create the sub-rows table
CREATE TABLE IF NOT EXISTS spreadsheet_sub_rows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  row_id BIGINT REFERENCES spreadsheet_rows(id) ON DELETE CASCADE,
  col_1 TEXT DEFAULT '',
  col_2 TEXT DEFAULT '',
  col_3 TEXT DEFAULT ''
);

-- Enable Row Level Security
ALTER TABLE spreadsheet_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE spreadsheet_sub_rows ENABLE ROW LEVEL SECURITY;

-- Create policies to allow all operations for now (since we don't have auth implemented yet)
-- Policy for spreadsheet_rows
CREATE POLICY "Enable all access for spreadsheet_rows" ON spreadsheet_rows
  FOR ALL USING (true) WITH CHECK (true);

-- Policy for spreadsheet_sub_rows
CREATE POLICY "Enable all access for spreadsheet_sub_rows" ON spreadsheet_sub_rows
  FOR ALL USING (true) WITH CHECK (true);
