// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: qiutgksttdrcdxgplldk

class SupabaseConfig {
  static const String supabaseUrl = 'https://qiutgksttdrcdxgplldk.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpdXRna3N0dGRyY2R4Z3BsbGRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MDYzNTYsImV4cCI6MjA4NjQ4MjM1Nn0.bvJFCqPWwYI9BDFz_yVnEr564zAV7uWnlIHFuDp7YsY';
}
